# Generated by Django 5.0.6 on 2026-05-26 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=20)),
                ('ingestion_method', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.company')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_id', models.CharField(blank=True, max_length=200)),
                ('scope_category', models.CharField(choices=[('scope1', 'Scope 1'), ('scope2', 'Scope 2'), ('scope3', 'Scope 3')], max_length=20)),
                ('activity_type', models.CharField(max_length=120)),
                ('activity_date', models.DateField()),
                ('raw_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('raw_unit', models.CharField(blank=True, max_length=40)),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('flagged', 'Flagged'), ('approved', 'Approved'), ('locked', 'Locked')], default='pending', max_length=20)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=120)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('origin', models.CharField(blank=True, max_length=10)),
                ('destination', models.CharField(blank=True, max_length=10)),
                ('traveler', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.company')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingestion.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=120)),
                ('previous_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(blank=True, max_length=120)),
                ('change_reason', models.TextField(blank=True)),
                ('change_type', models.CharField(choices=[('edit', 'Edit'), ('status', 'Status'), ('lock', 'Lock')], default='edit', max_length=20)),
                ('emission_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.emissionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingest_type', models.CharField(choices=[('file', 'File'), ('api', 'API'), ('manual', 'Manual')], max_length=20)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('records_total', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('records_suspicious', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.company')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingestion.datasource')),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.ingestionbatch'),
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('raw_payload', models.JSONField()),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('failed', 'Failed')], default='parsed', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.ingestionbatch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingestion.company')),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ingestion.datasource')),
            ],
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='raw_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.rawrecord'),
        ),
    ]
